#PYTHON METHOD'S
print("-----------------------------------------------------------------------------------")
print("1. String Operation : ")
print("-----------------------------------------------------------------------------------")
print("Length of string : ", len("Hello World"))
print("Upper case : ", "hello".upper())
print("Lower case : ", "HELLO".lower())
print("Minimum value : ", min([5, 2, 8, 1, 9]))
print("Maximum value : ", max([5, 2, 8, 1, 9]))
print("Sorted list : ", sorted([5, 2, 8, 1, 9]))
print("Title :", "hello world".title())
print("Capitalized :", "hello world".capitalize())
print("Split :", "Hello World".split())
print("Replace :", "Hello World".replace("World", "Python"))
print("Join :", "-".join(["Hello", "World"]))
print("Find :", "Hello World".find("World"))
print("Starts With :", "Hello World".startswith("Hello"))
print("endswith :", "Hello World".endswith("World"))
print("Swapcase :", "Hello World".swapcase())
print("Strip :", "   Hello World   ".strip())
print("Rstrip :", "   Hello World   ".rstrip())
print("IsAlpha :", "Hello".isalpha())
print("IsDigit :", "123".isdigit())
print("-----------------------------------------------------------------------------------")
print("2. List Operation : ")
print("-----------------------------------------------------------------------------------")
num_list = [1, 2, 3, 4, 5]
num_list.append(6)
print("Append :", num_list) 
num_list.extend([7, 8, 9])
print("Extend :", num_list)
num_list.insert(0, 0)
print("Insert :", num_list)
num_list.remove(3)
print("Remove :", num_list)
num_list.pop()
print("Pop :", num_list)
num_list.sort()
print("Sort :", num_list)
num_list.reverse()
print("Reverse :", num_list)
print("Index of 4 :", num_list.index(4))
print("Count of 2 :", num_list.count(2))
print("Length of list :", len(num_list))
print("Clear list : ", num_list.clear())
print("-----------------------------------------------------------------------------------")
print("3. Dictionary Operation : ")
print("-----------------------------------------------------------------------------------")
my_dict = {"name": "Alice", "age": 30, "city": "New York"}
print("Dictionary :", my_dict)
print("Keys :", my_dict.keys())
print("Values :", my_dict.values())
print("Items :", my_dict.items())
print("Get name :", my_dict.get("name"))
print("Update age :", my_dict.update({"age": 31}))
print("Updated Dictionary :", my_dict)
print("Pop city :", my_dict.pop("city"))
print("Dictionary after pop :", my_dict)
print("Clear Dictionary : ", my_dict.clear())
print("-----------------------------------------------------------------------------------")
